FROM node:20-alpine
WORKDIR /app
COPY services/api-gateway/package*.json ./
RUN npm install
COPY services/api-gateway/src ./src
COPY services/api-gateway/.env.example ./.env
EXPOSE 8080
CMD ["npm", "run", "dev"]
