FROM node:20-alpine
WORKDIR /app
COPY services/shared /app/shared
COPY services/fraud-detection-service/package*.json ./
RUN npm install
COPY services/fraud-detection-service/src ./src
COPY services/fraud-detection-service/.env.example ./.env
EXPOSE 3005
CMD ["npm", "run", "dev"]
